apiVersion: v1
kind: Secret
metadata:
  name: objectstorage-provisioner
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: driver-ibm
    app.kubernetes.io/version: main
    app.kubernetes.io/name: cosi-driver-ibm
type: Opaque
stringData:
  ENDPOINT: ""
  ACCESSKEY: ""
  SECRETKEY: ""
