kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: provisioner-role-binding
 namespace: ibm-cosi-driver
subjects:
- kind: ServiceAccount
  name: objectstorage-provisioner-sa
  namespace: ibm-cosi-driver
roleRef:
 kind: Role
 name: objectstorage-provisioner-role-test
 apiGroup: rbac.authorization.k8s.io
