apiVersion: v1
kind: Pod
metadata:
  name: awscli2
spec:
  containers:
    - name: awscli2
      # TODO: Replace the image with an official one once Amazon  publishes theirs
      image: mikesir87/aws-cli:1.16.220
      stdin: true
      tty: true
      volumeMounts:
        - name: cosi-secrets
          mountPath: /root/.aws
  volumes:
  - name: cosi-secrets
    csi:
      driver: objectstorage.k8s.io
      volumeAttributes:
        bar-name: demo-bar2
        bar-namespace: default
