apiVersion: v1
kind: Pod
metadata:
  name: awscli
spec:
  containers:
    - name: awscli
      # TODO: Replace the image with an official one once Amazon  publishes theirs
      image: mikesir87/aws-cli:latest
      stdin: true
      tty: true
      volumeMounts:
        - name: cosi-secrets
          mountPath: /data/cosi
        - name: bucket-name
          mountPath: /data/bucket
  volumes:
  - name: cosi-secrets
    csi:
      driver: objectstorage.k8s.io
      volumeAttributes:
        bar-name: demo-bar
        bar-namespace: default
  - name: bucket-name
    configMap:
      name: bucket-data
