apiVersion: v1
kind: Pod
metadata:
  name: ibmcli
spec:
  containers:
    - name: ibmcli
      image: ibmcom/ibm-cloud-developer-tools-amd64
      stdin: true
      tty: true
      volumeMounts:
        - name: cosi-secrets
          mountPath: /data/cosi
  volumes:
  - name: cosi-secrets
    csi:
      driver: objectstorage.k8s.io
      volumeAttributes:
        bar-name: demo-bar2
        bar-namespace: default