---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 namespace: ibm-cosi-driver
 name: objectstorage-provisioner-role-test
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: provisioner-role-binding
 namespace: ibm-cosi-driver
subjects:
- kind: ServiceAccount
  name: objectstorage-provisioner-sa
  namespace: ibm-cosi-driver
roleRef:
 kind: Role
 name: objectstorage-provisioner-role-test
 apiGroup: rbac.authorization.k8s.io
# ---
# kind: ClusterRole
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#  namespace: default
#  name: objectstorage-provisioner-role-cluster
# rules:
# - apiGroups: [""]
#   resources: ["configmaps"]
#   verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# ---
# kind: ClusterRoleBinding
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#  name: provisioner-role-binding-cluster
#  namespace: default
# subjects:
# - kind: ServiceAccount
#   name: objectstorage-provisioner-sa
#   namespace: default
# roleRef:
#  kind: ClusterRole
#  name: objectstorage-provisioner-role-cluster
#  apiGroup: rbac.authorization.k8s.io